ALTER TABLE "Group"
DROP COLUMN IF EXISTS "botPromptArtifactId",
DROP COLUMN IF EXISTS "botPromptText";

ALTER TABLE "User"
DROP COLUMN IF EXISTS "isBot",
DROP COLUMN IF EXISTS "botSlug",
DROP COLUMN IF EXISTS "botKind";

DROP TABLE IF EXISTS "BotDispatchRecord" CASCADE;
DROP TABLE IF EXISTS "GroupBotBinding" CASCADE;
DROP TABLE IF EXISTS "BotAgent" CASCADE;
DROP TABLE IF EXISTS "BotRuntimeConfig" CASCADE;
DROP TABLE IF EXISTS "GroupMemberContextTag" CASCADE;
DROP TABLE IF EXISTS "OpsRecord" CASCADE;
DROP TABLE IF EXISTS "AdminPendingItem" CASCADE;
DROP TABLE IF EXISTS "ActionProposal" CASCADE;
DROP TABLE IF EXISTS "GroupAiList" CASCADE;
DROP TABLE IF EXISTS "GroupAiReviewState" CASCADE;
DROP TABLE IF EXISTS "GroupAiAutonomyConfig" CASCADE;
DROP TABLE IF EXISTS "AiAutonomyRuntimeConfig" CASCADE;

DROP TYPE IF EXISTS "BotDispatchStatus";
DROP TYPE IF EXISTS "BotKind";
DROP TYPE IF EXISTS "GroupMemberContextTagType";
DROP TYPE IF EXISTS "OpsRecordType";
DROP TYPE IF EXISTS "AdminPendingItemType";
DROP TYPE IF EXISTS "AdminPendingItemPriority";
DROP TYPE IF EXISTS "AdminPendingItemStatus";
DROP TYPE IF EXISTS "ActionProposalStatus";
DROP TYPE IF EXISTS "GroupAiReviewStatus";
DROP TYPE IF EXISTS "GroupAiListKind";
