ALTER TYPE "GroupWorkStatus" RENAME VALUE 'DISCOVERY' TO '初始';
ALTER TYPE "GroupWorkStatus" RENAME VALUE 'WAITING_OWNER' TO '优先';
ALTER TYPE "GroupWorkStatus" RENAME VALUE 'WAITING_ADMIN' TO '打包';
ALTER TYPE "GroupWorkStatus" RENAME VALUE 'IN_PROGRESS' TO 'ing';
ALTER TYPE "GroupWorkStatus" RENAME VALUE 'BLOCKED' TO '阻塞';
ALTER TYPE "GroupWorkStatus" RENAME VALUE 'PAUSED' TO '暂停';
ALTER TYPE "GroupWorkStatus" RENAME VALUE 'DONE' TO '完成';
ALTER TYPE "GroupWorkStatus" RENAME VALUE 'CANCELLED' TO '取消';
